services:
  mixify:
    image: ${TAG_PROD}
    restart: always
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 app:app --access-logfile '-' --error-logfile '-'
    env_file:
      - .env
    networks:
      - mixify_internal
    volumes:
      - ./.flask_session:/home/app/.flask_session
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mixify_internal:
    external: true
