stages:
  - test
  - build
  - deploy

job-test:
  stage: test
  image: python:alpine3.17
  script:
    - pip install -r services/web/requirements.txt
    # - python manage.py test
  tags:
    - docker

job-build:
  stage: build
  image: docker:20.10
  # services:
  #   - docker:20.10-dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  script:
    - pwd
    - ls -lah
    # - cd services/web/
    - docker ps -a
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} registry.timych.ru
    - docker system info
    - docker build -t registry.timych.ru/timych/mixify services/web/.
    - docker push registry.timych.ru/timych/mixify
  tags:
    - docker
