variables:
  KUBE_CONTEXT: timych/k8s-connection:k8s-connection

stages:
  - test
  - build
  - deploy

job-test:
  stage: test
  image: python:alpine3.17
  script:
    - pip install -r services/web/requirements.txt
    # - python manage.py test
  tags:
    - k8s

job-build:
  stage: build
  image: docker:20.10
  # services:
  #   - docker:20.10-dind
  # variables:
  #   DOCKER_TLS_CERTDIR: "/certs"
  variables:
    IMAGE_NAME: timych/mixify:${CI_COMMIT_SHORT_SHA}

  script:
    - pwd
    - ls -lah
    - echo ${CI_PROJECT_PATH}
    # - cd services/web/
    - docker ps -a
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker system info
    - docker build -t ${CI_REGISTRY}/${IMAGE_NAME} services/web/.
    - docker push ${CI_REGISTRY}/${IMAGE_NAME}
  tags:
    - docker

job-deploy:
  stage: deploy
  image:
    name: dtzar/helm-kubectl:3.14
    entrypoint: ['']
  before_script:
    - echo ${kube_config}
  script:
    - ls -la
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl get pods
    - kubectl get nodes -o wide
    - helm list -A
    - echo $KUBE_CONFIG
    - helm upgrade mixiy-v1 mixify --install --namespace mixify-v1 --create-namespace --set mixifySpec.clientid=$MIXIFY_CLIENTID --set mixifySpec.clientsecret=$MIXIFY_CLIENTSECRET
  tags:
    - k8s
