replicaCount: 1

mixifyImage:
  repository: registry.timych.ru/timych/mixify/master
  tag: "latest"
  pullPolicy: Always

mixifySpec:
  targetPort: 5000
  clientid: default_client_id
  clientsecret: default_client_secret
  redirecturi: 'http://your-spotify-redirect.url'
  url: your-spotify-redirect.url

service:
  name: multitool-service
  type: ClusterIP
  httpPort: 9002
  httpsPort: 9443
