apiVersion: v1
kind: Secret
metadata:
  name: mixify-secret
data:
  mixify.clientid: {{ .Values.mixifySpec.clientid | b64enc }}
  mixify.clientsecret: {{ .Values.mixifySpec.clientsecret | b64enc }}
  mixify.redirecturi: {{ .Values.mixifySpec.redirecturi | b64enc }}
